#
# Makefile for the IEEE 802.1d ethernet bridging layer.
#

obj-${CONFIG_NTRACK} += ntrack.o
ntrack-y	:= \
	ntrack_hooks.o \
	ntrack_msg.o \
	ntrack_conf.o \
	ntrack_auth.o \
	nt_firewall.o \
	nt_mroute.o \
	nt_redirect.o \
	context_check.o \
	nxjson.o

