#pragma once

enum __em_inner_proto {
	NP_INNER_RULE_HTTP_REQ = 1,
	NP_INNER_RULE_HTTP_REP,
	NP_INNER_RULE_HTTP_SVN,
	NP_INNER_RULE_SMTP,
	NP_INNER_RULE_POP3,
	NP_INNER_RULE_SSH,
	NP_INNER_RULE_SSL,
	NP_INNER_RULE_FTP,
	NP_INNER_RULE_DHCP,
	NP_INNER_RULE_SMB,
	NP_INNER_RULE_RDP,
	NP_INNER_RULE_SIP,
	NP_INNER_RULE_NTP,
	NP_INNER_RULE_VNC,
	NP_INNER_RULE_GTalk,
	NP_INNER_RULE_MAX,
};