#!/bin/sh
# Copyright (C) 2006-2011 OpenWrt.org

NP_CRC_FILE='/etc/nproto/applist.conf'
NP_INNER_DUMP='/proc/nproto/dump'

mkdir -p '/etc/nproto/'

#TODO translate format.
cat "$NP_INNER_DUMP" | sort -u > "$NP_CRC_FILE"