#!/bin/sh /etc/rc.common
START=93
STOP=20

FSYS='/sys/module/tbq/tbq'

boot() {
	start
	return 0
}

reload() {
	stop
	rmmod tbq
	modprobe tbq
	start
	return 0
}

restart() {
	stop
	sleep 1
	start
}

start() {
	echo 0 > ${FSYS}
	lua /usr/sbin/settc.lua /etc/config/tc.json | cat > ${FSYS}
	echo 1 > ${FSYS}
}
stop() {
	return 0
}
